bind_addr = ":3000"
log_level = "debug"
database_url = "host=localhost port=5432 user=postgres password=postgres dbname=rest_api_dev sslmode=disable"
session_key = "8a90558be70ca9682c6f86223782550489ccfdb20f155f1a8b3182781dc60447"
